export ARTIFACTORY="https://qartifactory-edge.qualcomm.com/artifactory/qsc_releases/software/chip/component/computervision-sv.qclinux.0.0"
export TAG="260604"
export DISTRO="prebuilt_resolute"
#export PACKAGE_NAME="btftm_1.0.2_arm64.tar.gz"
